"""Update interpretation without compressing the approved chapter structure."""
from pathlib import Path
import re

WORK=Path(__file__).resolve().parents[1]
P=WORK.parent/'paper_en_partc_cv5'

def paragraph(text, prefix, replacement):
    start=text.index(prefix)
    end=text.find('\n\n',start)
    if end<0:end=len(text)
    return text[:start]+replacement.strip()+text[end:]

def main():
    path=P/'sections_en/05_06_discussion_conclusion.tex'
    s=(WORK/'source_base/sections_en/05_06_discussion_conclusion.tex').read_text(encoding='utf-8')
    s=paragraph(s,'This study evaluated the potential',r'''This study evaluated the potential of LLMs to serve as travel agents by examining both out-of-fold choice prediction and behavioral alignment under changed service conditions. Comparing zero-shot and SFT systems provided preliminary evidence that learning observed choices may support selected behavioral capabilities needed for this role. The results also distinguish changes in response level and distribution from changes in directional and subgroup consistency. The discussion considers these findings in four parts. Section~\ref{sec:disc-transfer} discusses behavioral adjustments associated with final-choice learning. Section~\ref{sec:disc-correspondence} examines correspondence between inferred economic relationships and Direct response distributions. Section~\ref{sec:disc-heterogeneity} considers the representation of behavioral heterogeneity. Section~\ref{sec:limitations} addresses the scope of the five-fold evidence and directions for further training and application-level validation.''')
    s=paragraph(s,'The SFT objective in this study',r'''The SFT objective in this study learned final adoption and retention outcomes. Fare elasticity, the relative responses to time and cost, and subgroup contrasts were not supplied as separate behavioral targets. Nevertheless, the two Qwen scales began with different mean fare elasticities and both moved toward the survey-based mean in the main probability analysis. Their Direct VOT distributions also narrowed, especially for 9B, and both medians became closer to the fitted human reference. These observations suggest that final-choice learning can be accompanied by changes in service-response properties beyond classification performance. The changes were selective: 2B fare-elasticity dispersion increased, and the share of computable VOT cases with both component slopes negative decreased at both scales. A closer average or a narrower ratio distribution therefore does not establish improvement in all aspects of behavioral response.''')
    s=paragraph(s,'Applying the common discrete-choice specification',r'''Applying the common discrete-choice specification to generated choices offers a complementary view. Fare remained negatively associated with adoption in every Qwen projection. The survey-based IVT estimate was less precisely identified than fare, and both SFT BASE projections had VOT confidence sets that included zero. Closer point estimates must therefore be distinguished from precise recovery of a positive time value. Demographic and socioeconomic associations also varied across the survey and generated-choice fits. These coefficients describe relationships under the analyst's specification; they do not reveal internal variable importance or establish recovery of the population's preferences. Moreover, coefficients from separate logit fits incorporate utility scale, so changes in their absolute magnitudes cannot alone establish that the LLM assigns more or less behavioral importance to a variable. Their value here is diagnostic when considered alongside directly measured probability responses.''')
    s=paragraph(s,'The comparison involves three objects.',r'''The comparison involves three objects. The survey-based reference summarizes all retained human choices through an estimated model. The generated-choice estimates describe what the same econometric specification infers from the pooled out-of-fold choices. The Direct distributions retain variation in the assigned models' responses across traveler--trip contexts and service intervals. For SFT, the pooled representation combines outputs from five adapters, while each case and all of its edited conditions use the same frozen adapter. These objects answer different questions. Direct is not intended to reproduce one coefficient-based VOT at every case, but to describe the location, dispersion, tails, and signs of response relationships across cases.''')
    s=paragraph(s,'A generated-choice VOT close',r'''A generated-choice VOT close to the survey estimate may occupy a different range from the center of the agent's Direct distribution. Conversely, an economic estimate can fall near that center even when both differ from the survey reference. The zero-shot results illustrate why the two comparisons cannot be combined into one judgment of behavioral validity. After SFT, fare-elasticity gaps decreased in both sizes, while VOT correspondence depended on size and representation: 9B BASE and CF gaps decreased, but the 2B BASE-to-Direct VOT gap increased slightly. Table~\ref{tab:tab07} supplies these scalar comparisons alongside the figures. Such gaps do not measure complete distributional correspondence, and reductions in them cannot substitute for examining the signs and spread of the underlying responses.''')
    s=paragraph(s,'The subgroup analysis identifies',r'''The subgroup analysis identifies a further distinction between changing an overall response and reproducing its structure within a population. Although mean fare elasticity became more comparable with the survey-based reference and Direct VOT distributions narrowed, subgroup contrasts changed less consistently. Age-related mean fare differences moved toward the selected human pattern but remained much smaller. Both SFT systems retained a sex ordering in mean fare elasticity opposite to the fitted reference, while their age and sex VOT differences were also substantially smaller. These features would be obscured if behavioral alignment were evaluated only through a population mean or the width of the overall distribution.''')
    s=paragraph(s,'The present evidence comes from',r'''The present evidence comes from one AV stated-preference setting and two scales of one LLM family. The five-fold analysis was assembled after the earlier fixed-split analysis and is a retrospective extension, not a preregistered independent replication. All candidate predictions exclude their respondent from the assigned training fold, but the evaluated cohort remains the common 651 respondents and 3,468 cases with completed outputs, rather than all held-out cases across the full five-fold survey. The task is conditional adoption: retention means keeping the exact incumbent mode, and switches between conventional modes are excluded. Some persona inputs were collected after the SP tasks. The findings therefore concern retrospective conditional response emulation, with broader generalization requiring additional populations, choice settings, and prospectively available persona information.''')
    s=paragraph(s,'The implementation also places limits',r'''The conventional candidates were refitted using respondent-grouped inner tuning within each outer training sample, with fold metadata excluded from predictors. Their historical class-treatment rules were held fixed; the five-fold results were not used to choose new settings. This removes evaluation-fold feedback from the current tuning procedure, but does not turn the historically developed comparison protocol into a prospective design. ZS and SFT also use different answer-format instructions, so their differences cannot be attributed to weight updates alone. Five adapters per SFT scale account for fold-specific training evidence, but do not replace repeated training seeds or identical-interface experiments. The pooled economic projections describe the cross-fitted system; seven of the twenty fold-specific BASE projections encountered separation, limiting adapter-level confirmation. These limits qualify the interpretation of pooled correspondence.''')
    s=paragraph(s,'Probability definition and reference uncertainty',r'''Probability definition affects both predictive and behavioral comparisons. The main Qwen analysis uses pair-normalized unadjusted answer probabilities. Adding the log odds of each fold's training adoption prevalence lowers pooled BASE Log Loss for both SFT systems, but also lowers AV recall; it increases Log Loss for 9B ZS. It changes the elasticity and VOT levels as well. Under this alternative definition, both SFT aggregate VOT estimates remain closer to the reference than their corresponding ZS estimates, although the size of the reduction changes. A lower prediction loss therefore does not by itself select the appropriate behavioral probability definition. The raw and adjusted results must be read with denominator sensitivity, component signs, and the intended interpretation of the model's answer probabilities.''')
    anchor='Future training studies can compare'
    index=s.index(anchor)
    uncertainty=r'''Reference uncertainty further limits the interpretation. H-MNL and the subgroup model are fitted to all 2,169 retained survey respondents, including those in the common evaluation cohort. They are descriptive references, not independently validated predictions of human counterfactual choices. In 200 linked respondent bootstrap replicates, the same respondent receives the same resampling multiplicity in reference fitting and evaluation. The 95\% intervals for the reduction in the absolute aggregate-VOT gap are $[-7.077,\,7.239]$ for 2B and $[4.756,\,21.316]$ for 9B, in $10^3$~KRW/h. The corresponding mean fare-elasticity-gap intervals are $[0.124,\,0.175]$ and $[-0.184,\,0.477]$. Thus, the supported contrast depends on the behavioral measure and model size. These intervals condition on the existing trained models and do not include their retraining uncertainty or uncertainty about the reference specification.'''
    s=s[:index]+uncertainty+'\n\n'+s[index:]
    s=paragraph(s,'This study examined how supervised fine-tuning',r'''This study examined how supervised fine-tuning on human travel choices changes both predictive performance and behavioral responses of LLM travel agents. It connects persona-based zero-shot behavior with efforts to learn observed respondent choices and extends their evaluation to changed AV service conditions. The retrospective five-fold analysis evaluates a common cohort using the model assigned to each respondent's held-out fold. Within the same traveler--trip contexts, it measures probability responses, fare elasticity, time--cost response ratios, and subgroup contrasts. It also examines whether economic relationships inferred from pooled generated choices characterize the Direct distributions of those same assigned agents.''')
    s=paragraph(s,'After SFT, Macro-F1, AV-class F1',r'''After SFT, mean Macro-F1, AV-class F1, and AV recall improved relative to zero-shot performance at both scales. Mean Log Loss also decreased, although the 9B reduction was small, and Accuracy improved for 2B but decreased for 9B. The evidence therefore supports improved adoption identification and a more balanced adoption--retention classification, while keeping probability quality and overall accuracy separate. The comparison with conventional models remains specific to the metric. For a conditional adoption task with relatively few adopters, this distinction separates recovering AV adoption from correctly predicting the more common retention outcome.''')
    s=paragraph(s,'Behavioral properties also changed',r'''Behavioral properties also changed after choice-based training. The two scales began with different mean fare elasticities and both moved toward the survey-based mean. Their Direct VOT distributions narrowed, and their medians became closer to the reference, with a more pronounced change for 9B. These responses were not supplied as separate SFT targets: the training signal concerned respondents' final choices. However, the expected-sign share of computable VOT cases decreased, and 2B fare-elasticity dispersion increased. The observations consequently show that final-choice learning can accompany selective behavioral adjustments, with response level, spread, and direction requiring distinct evaluation.''')
    s=paragraph(s,'The generated-choice analysis contributed',r'''The generated-choice analysis contributed a complementary result. An elasticity or VOT inferred under the original conditions did not necessarily characterize the range of Direct responses under changed conditions. Fare-elasticity correspondence gaps decreased after SFT at both scales; VOT gaps decreased strongly for 9B, whereas the 2B BASE-to-Direct gap increased slightly despite a smaller CF-to-Direct gap. Agreement between summary values did not establish correspondence between whole distributions. The fitted GC-MNL VOT distributions remained much narrower under the same numerical calculation, showing the limits of that specified economic representation. Economic interpretation and direct response evaluation therefore provide complementary evidence about the trained system.''')
    s=paragraph(s,'The scope of the present evidence remains conditional.',r'''The scope of the evidence remains conditional. The full-survey human references are descriptive and model-based, with an uncertain IVT coefficient and VOT confidence set including zero. Linked resampling supports a reduction in the aggregate-VOT reference gap for 9B, while the 2B interval includes zero; mean fare-elasticity comparisons have a different uncertainty pattern. The evaluation covers a common subset of a retrospectively assembled five-fold experiment, one LLM family, and state-specific answer instructions. Fold-specific economic projections are not all estimable, and the analysis does not include repeated SFT seeds or a running transport simulation. These limits identify the additional evidence needed for other populations and policy applications.''')
    s=s.replace('in every Qwen projection.','in every pooled Qwen projection.')
    s=s.replace('Both SFT systems retained a sex ordering','Both SFT systems exhibited a sex ordering')
    s=s.replace('the five-fold results were not used to choose new settings.','held-out outer-fold outcomes were not used to choose settings.')
    path.write_text(s,encoding='utf-8')
    main=P/'main_en.tex';t=main.read_text(encoding='utf-8')
    a=t.index('\\begin{abstract}')+len('\\begin{abstract}');b=t.index('\\end{abstract}',a)
    abstract=r'''Large language models (LLMs) offer potential as synthetic travelers, but transport analysis requires both credible choice prediction and appropriate responses to changing service conditions. Existing studies have examined zero-shot travel behavior and improved prediction through supervised fine-tuning (SFT), largely as separate strands. Whether learning observed choices can improve both capabilities and adapt an LLM's behavior to a target population therefore requires direct evaluation.

Using autonomous ride-hailing stated-preference data from the Seoul metropolitan area, we compare persona-conditioned zero-shot and SFT versions of Qwen3.5 2B and 9B with conventional choice, machine-learning, and deep-learning models. A retrospective respondent-level five-fold analysis evaluates a common cohort of 651 respondents and 3,468 cases using out-of-fold predictions. We directly measure responses to fare, travel-time, and waiting/access-time changes within fixed traveler--trip contexts. Fare elasticity and value-of-travel-time (VOT) distributions are compared with descriptive references fitted to the full retained survey and economic estimates inferred from generated choices.

Qwen SFT improved adoption identification and Macro-F1 at both scales. Log Loss decreased, though only slightly for 9B, while Accuracy changed unevenly. Mean fare elasticity moved closer to the survey-based reference, and VOT distributions narrowed with medians nearer that reference. Fare-elasticity correspondence gaps decreased at both scales, whereas VOT correspondence improved more consistently for 9B. These changes emerged without explicit behavioral targets, supporting the potential for choice-based training to improve selected behavioral properties alongside prediction. Remaining response-direction and subgroup differences, together with reference uncertainty, motivate further validation using more diverse human-choice data and targeted behavioral training.'''
    t=t[:a]+'\n'+abstract+'\n'+t[b:];main.write_text(t,encoding='utf-8')
    # Historical rules are fixed in this extension, not prospectively preregistered.
    for f in [P/'sections_en/03_method.tex',P/'sections_en/appendix.tex']:
        t=f.read_text(encoding='utf-8').replace('predeclared class-treatment rule','previously fixed class-treatment rule')
        f.write_text(t,encoding='utf-8')
    c=s[s.index('\\section{Conclusion}'):]
    pars=[x for x in c.split('\n\n') if x.strip() and not x.lstrip().startswith('\\')]
    assert len(pars)==9,len(pars)
    print('Abstract, Discussion, and nine-paragraph Conclusion updated.')

if __name__=='__main__':main()
