"""Update protocol statements only in the separate CV5 manuscript."""
from pathlib import Path
import re
WORK=Path(__file__).resolve().parents[1]
PAPER=WORK.parent/'paper_en_partc_cv5'

def paragraph(text,prefix,new):
    parts=text.split('\n\n');idx=[i for i,p in enumerate(parts) if p.startswith(prefix)]
    assert len(idx)==1,(prefix,idx)
    parts[idx[0]]=new
    return '\n\n'.join(parts)

def main():
    p=PAPER/'sections_en/03_method.tex';s=p.read_text(encoding='utf-8')
    s=paragraph(s,'This study evaluates LLM travel agents',r'''This study evaluates LLM travel agents from two perspectives: choice prediction and behavioral response. It uses two types of human evidence, each playing a different role. Observed choices are compared with respondent-level out-of-fold predictions; a logit fitted to the full retained survey provides a descriptive behavioral reference. The primary comparison is the shift from persona-conditioned Qwen zero-shot to SFT, with conventional travel-choice models providing context. We first define the SP sample and input information, then generate choices and probabilities under original and changed service conditions, and finally assess prediction, behavioral alignment, and correspondence between choice-based estimates and each agent's direct response. Figure~\ref{fig:method-overview} summarizes this sequence; Table~\ref{tab:method-terms} groups the abbreviations and analytical labels by role.''')
    s=paragraph(s,'The development and evaluation samples were separated',r'''The retained sample contains 2,169 respondents and 11,584 observations. Respondents were assigned to five mutually exclusive folds; all tasks from a respondent remain in the same fold. For each fold, SFT and the conventional predictive models use the other four folds for training. Conventional-model tuning and preprocessing use only those training respondents. The five training samples contain 9,230--9,297 cases from 1,735--1,736 respondents. The final fold-specific models are frozen before evaluating that fold.

The main comparison uses a common subset of 651 respondents and 3,468 cases for which all four Qwen states have complete BASE and counterfactual outputs. This is the evaluation cohort from the earlier fixed-split experiment, distributed across the five folds here. Its fold-specific case counts are 752, 727, 643, 680, and 666. Each case is scored by a model trained without its respondent, using the same frozen model for BASE and every service change. The analysis therefore pools out-of-fold responses on this common cohort; it does not report counterfactual coverage for all 11,584 cases. Because the five-fold design was constructed after earlier analysis of the survey, the comparison is retrospective rather than a newly untouched final test.

The human behavioral references use all 11,584 observed choices, including the common evaluation cohort. They summarize economic relationships in the retained survey and are not independent out-of-sample prediction benchmarks. This full-sample reference is kept separate from the fold-specific predictive candidates and is evaluated at the same 3,468 traveler--trip contexts for behavioral comparisons.''')
    s=s.replace('an SFT state trained on human development choices','an SFT state trained on the other four respondent folds')
    s=s.replace('a reference estimated from development choices','a descriptive reference estimated from all retained survey choices')
    s=s.replace('a model learns observed final choices from development respondents','a model learns observed final choices from respondents in its training folds')
    s=s.replace('Human-reference MNL fitted to observed development choices','Human-reference MNL fitted to all retained observed survey choices')
    s=paragraph(s,'Conventional models receive the inputs',r'''Conventional models receive the inputs described in Section~\ref{sec:method-data}, excluding identifiers, fold labels, and outcome-dependent variables. For each model and outer fold, the same fitted probability function supplies BASE prediction and service-condition responses. Seed 42 is used for tuning and fitting; uncertainty across repeated training seeds is not assessed. The generated-choice projections and Direct responses use the same fold-assigned fits. Qwen SFT likewise keeps each evaluated respondent's assigned adapter fixed across all conditions, while ZS has no fold-dependent fitted state. Appendix~\ref{app:candidate-hyperparameters} reports the training-only inner tuning and class-treatment rules. The benchmark labeled Pooled logit is a class-weighted pooled binary logit; it has no respondent-specific random effect or panel likelihood.''')
    s=s.replace('The final adapters were then frozen for prediction and behavioral analysis.','The final adapter from each fold was then frozen for prediction and behavioral analysis. Thus, each SFT scale is represented by five adapters, with a fixed adapter assigned to every evaluated respondent; ZS uses one unchanged pre-trained model partitioned by the same fold labels for reporting.')
    s=s.replace('the fixed development-prior adjustment used during training','the corresponding fold-training-prior adjustment used during SFT')
    s=s.replace(r'A constant probability equal to the development AV share, $1{,}528/8{,}116$, supplies a simple baseline without using evaluation outcomes to choose its probability.',r'A constant probability equal to the AV share in the other four training folds supplies a fold-specific baseline without using the evaluated respondent\textquotesingle s outcome to choose its probability. Table~\ref{tab:tab01} reports the arithmetic mean and sample standard deviation of the five fold-specific metrics on the common cohort. The standard deviation describes differences across these folds; it is not a confidence interval or variation across repeated training seeds.')
    s=s.replace(r'respondent\textquotesingle s',"respondent's")
    s=paragraph(s,'The survey-based H-MNL is fitted',r'''The survey-based H-MNL is fitted once to all 11,584 retained observed choices. It does not represent humans' unobserved counterfactual choices; it provides a descriptive empirical reference for this survey. To compare responses on the same basis, its probabilities are evaluated for the common 3,468 contexts at BASE and along the same edited ladders. Equation~\eqref{eq:central-difference} and the Direct definitions in Table~\ref{tab:method-measures} then give corresponding human-reference responses, interval elasticities, and time--cost ratios. Coefficient signs and uncertainty are examined before interpreting each attribute as a behavioral reference. Appendix~\ref{app:human-references} distinguishes the reference specifications used for overall and subgroup comparisons.''')
    s=s.replace('a separate development-sample interaction reference','a separate full-sample interaction reference')
    s=paragraph(s,'For each candidate, GC-MNL uses predicted choices',r'''For each candidate, GC-MNL uses the pooled out-of-fold choices at BASE. CF-MNL adds the relevant predicted CF choices to examine whether a wider service-condition range improves the economic representation. Each fit pools generated outcomes from the five assigned models while retaining one common 23-parameter specification. The resulting coefficients summarize the cross-fitted system; they are not coefficients internal to a single adapter. We additionally examine fold-specific projections against the Direct responses of that fold's frozen model to check whether a pooled comparison conceals differences across adapters. Human and generated choices are never combined in one fit. CF-MNL is assessed on the generated conditions used in fitting, so it describes within-sample approximation; GC-MNL supplies the comparison from BASE-generated choices to changed conditions.''')
    s=paragraph(s,'To check whether the comparison depends',r'''To check whether the comparison depends on different numerical calculations, we also evaluate GC-MNL probabilities on the same service ladders and apply the same finite-difference and elasticity definitions as for Direct. Appendix~\ref{app:representation-check} reports this focused comparison for the four Qwen states. It describes the response function of the fitted economic representation without recalibrating the agent. For selected reference comparisons, 200 paired respondent-cluster bootstrap replicates re-estimate H-MNL from the full survey. Each draw uses the same respondent multiplicity for that person's human-reference observations and evaluated agent responses, preserving their overlap and the pairing between ZS and SFT. The resulting intervals describe sampling sensitivity conditional on the frozen runs and chosen specification; they do not measure SFT training-seed variation.''')
    p.write_text(s,encoding='utf-8')
    p=PAPER/'sections_en/appendix.tex';s=p.read_text(encoding='utf-8')
    s=s.replace('These transformations are fitted on development data.','These transformations are fitted separately on each outer training sample; tuning uses respondent-grouped inner folds. Fold labels and identifiers are retained for splitting and provenance only and are excluded from predictors.')
    s=paragraph(s,'The same selected configuration is used with seeds',r'''For each model and outer fold, three-fold respondent-grouped inner cross-validation selects hyperparameters using negative Log Loss on the four-fold training sample. The predeclared class-treatment rule is then applied consistently. Seed 42 is used throughout. Each fitted model generates both BASE and all CF probabilities for its evaluated respondents, so prediction, Direct measures, and generated-choice projections refer to the same fit. Hard choices use $p\geq0.5$, including SVM. Fold-specific settings and preprocessing inventories are retained in the reproducible analysis outputs. These are retrospective five-fold comparisons; no outcome in the evaluated outer fold is used to tune its candidate model.''')
    s=s.replace('Registered fixed-split Qwen SFT configuration.','Qwen SFT configuration for the five respondent folds.')
    s=s.replace('8,116 development cases; 1,528 AV and 6,588 Keep; seed 42','9,230--9,297 cases from four folds; 1,695--1,730 AV cases; seed 42')
    s=s.replace('Three epochs; 1,524 optimizer updates; paged AdamW 8-bit; gradient checkpointing','Three epochs; 1,731--1,746 optimizer updates; paged AdamW 8-bit; gradient checkpointing')
    s=s.replace('Final optimizer-step 1,524 adapter for each model size','Final adapter for every model size and fold; steps 1,737/1,740/1,746/1,731/1,740 for folds 1--5')
    s=s.replace(r'With $\pi_{AV}=1{,}528/8{,}116$ and $\pi_{Keep}=6{,}588/8{,}116$, training uses $p_i^*=\sigma[m_i+\log(\pi_{AV}/\pi_{Keep})]$. The log-prior shift is $-1.46129$, applied once to all three binary-loss components; the positive-class weight is 1.',r'For fold $f$, let $\pi_{AV,f}$ be the AV share among its training cases and $\pi_{Keep,f}=1-\pi_{AV,f}$. Training uses $p_i^*=\sigma[m_i+\log(\pi_{AV,f}/\pi_{Keep,f})]$. The log-prior shifts for folds 1--5 are $-1.48290$, $-1.47237$, $-1.49353$, $-1.48179$, and $-1.49809$, respectively. Each is applied once to all three binary-loss components; the positive-class weight is 1.')
    s=s.replace('The weights are documented in the shared source configuration and completed 2B training log; the 9B execution manifest records the composite objective and prior adjustment without separately repeating the component weights.','The component weights and prior adjustment are recorded in the completed training logs at both model sizes, and each final-adapter manifest records its training file, sample size, objective, and final step. Both sizes use the same fold assignments and three-epoch schedule.')
    s=s.replace('a separate development-sample interaction model','a separate full-sample interaction model fitted to the same 11,584 survey choices')
    s=s.replace('All retain the same 651 respondents and 23-parameter specification, with equal scenario weights and respondent-cluster covariance.','The generated-choice fits retain the same 651 respondents and 23-parameter specification, with equal scenario weights and respondent-cluster covariance. H-MNL uses all 2,169 survey respondents; its behavioral summaries are evaluated on the common 651-respondent cohort.')
    p.write_text(s,encoding='utf-8')
    print('Updated Methods and Appendix protocol in isolated CV5 copy.')

if __name__=='__main__': main()
